{% set name = "hatch-vcs" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0395fa126940340215090c344a2bf4e2a77bcbe7daab16f41b37b98c95809ff9

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatchling >=1.1.0
  run:
    - python
    - hatchling >=1.1.0
    - setuptools-scm >=8.2.0

# AssertionError: assert {'version': '0.5.0'} == {'version': '1.2.3'}
{% set deselect_tests = "--deselect=tests/test_version_config.py::TestTagPattern::test_custom_tag_pattern_get_version" %}

test:
  source_files:
    - tests
  imports:
    - hatch_vcs
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - git  # [linux]

about:
  home: https://pypi.org/project/hatch-vcs
  summary: Hatch plugin for versioning with your preferred VCS
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    This provides a plugin for Hatch that uses your preferred version
    control system (like Git) to determine project versions.
  dev_url: https://github.com/ofek/hatch-vcs
  doc_url: https://pypi.org/project/hatch-vcs

extra:
  recipe-maintainers:
    - nicoddemus
  skip-lints:
    - python_build_tool_in_run
    - missing_wheel
